sudo: required
services:
  - docker

before_install:
  - docker build -t stefanorigat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stefanorigat/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-601380712707"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY